name: Sonar
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 16 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: xdebug
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install dependencies
        run: >
          wget
          https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492.zip

          unzip sonar-scanner-cli-3.3.0.1492.zip

          composer --no-plugins --no-scripts install

          composer --no-plugins --no-scripts dump-autoload -o

          vendor/bin/phpunit --configuration ./phpunit.xml --teamcity
      - name: Sonar
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
          SONAR_PROJECT_NAME: '${{ secrets.SONAR_PROJECT_NAME }}'
          SONAR_PROJECT_KEY: '${{ secrets.SONAR_PROJECT_KEY }}'
          SONAR_ORGANIZATION: '${{ secrets.SONAR_ORGANIZATION }}'
        run: |
          sonar-scanner-3.3.0.1492/bin/sonar-scanner \
            -Dsonar.projectName=$SONAR_PROJECT_NAME \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORGANIZATION \
            -Dsonar.sources=./src \
            -Dsonar.tests=./tests \
            -Dsonar.exclusions=**/vendor/**,**/tests/**,**/*.xml \
            -Dsonar.php.tests.reportPath=tests.xml \
            -Dsonar.php.coverage.reportPaths=coverage.xml \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
