name: Build & Test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 16 * * *
jobs:
  build:
    strategy:
      matrix:
        php:
          - 5.6
          - 7
          - 7.1
          - 7.2
          - 7.3
          - 7.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php }}'
          coverage: none
      - name: Install dependencies
        run: |
          composer --no-plugins --no-scripts install
          composer --no-plugins --no-scripts dump-autoload -o
          vendor/bin/phpunit --configuration ./phpunit.xml --teamcity
