name: Build & Test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 16 * * *
jobs:
  build:
    strategy:
      matrix:
        include:
          - php: 5.6
            phpunit: 5
          - php: '7.0'
            phpunit: 6
          - php: 7.1
            phpunit: 7
          - php: 7.2
            phpunit: 8
          - php: 7.3
            phpunit: 9
          - php: 7.4
            phpunit: 9
          - php: '8.0'
            phpunit: 9

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: php${{ matrix.php }}-${{ hashFiles('**/composer.json') }}

    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: ${{ matrix.php }}

    - name: Run tests
      uses: php-actions/phpunit@v3
      with:
        php_version: ${{ matrix.php }}
        version: ${{ matrix.phpunit }}
